apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: dividas-destinationrule
spec:
  host: dividas
  subsets:
  - name: canario
    labels:
      version: release-2.0.0
  - name: atual
    labels:
      version: release-1.0.0
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: dividas-vs
spec:
  hosts:
    - dividas
  http:
  - match:
    - headers:
        canario:
          exact: "true"
    route:
      - destination:
          host: dividas
          subset: canario
  - route:
    - destination:
        host: dividas
        subset: atual