apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: contratos-destinationrule
spec:
  host: contratos
  subsets:
  - name: canario
    labels:
      version: release-2.0.0
  - name: atual
    labels:
      version: release-1.0.0
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: contratos-vs
spec:
  hosts:
    - contratos
  http:
  - route:
    - destination:
        host: contratos
        subset: canario
      weight: 10
      headers:
        request:
         add:
            canario: "true"
    - destination:
        host: contratos
        subset: atual
      weight: 90